version: '2'

services:
    application:
        container_name: application
        image: ubuntu
        volumes:
            - ./:/var/www/app
    workspace:
        container_name: workspace
        restart: always
        image: mrduong92/laravel-workspace
        volumes_from:
            - application
        tty: true

    php-fpm:
        container_name: php-fpm
        restart: always
        image: mrduong92/php7fpm
        volumes_from:
            - application
        links:
            - workspace

    nginx:
        container_name: nginx
        restart: always
        image: mrduong92/nginx
        volumes_from:
            - data
            - application
        ports:
            - "8080:80"
        links:
            - php-fpm

    phpmyadmin:
        image: busybox:1.26.2
        command: [/bin/sh, .docker/phpmyadmin/command.sh]
        volumes:
          - .:/var/www/app
        ports:
            - "6968:6968"
        working_dir: /var/www/app

    data:
        container_name: data
        image: ubuntu
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data

    mysql:
        container_name: mysql
        restart: always
        image: mysql
        volumes_from:
            - data
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

    redis:
        container_name: redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
